CREATE TABLE IF NOT EXISTS supplementTest (id int generated by default as identity (start with 1) primary key,
                                       entryDate DATE NOT NULL,
                                       supplementName VARCHAR NOT NULL,
                                       pubChemId bigint NOT NULL,
                                       description VARCHAR,
                                       lowerBoundaryDoseMG real,
                                       upperBoundaryDoseMG real);